[module]
arch = { version = "v0.1.8" }
vscode = { version = "v0.1.2" }
cargo = { version = "v0.1.2" }
npm = { version = "v0.1.1" }

[arch]
base-devel = { version = "1-2" }
discord = { version = "0.0.77-1" }
firefox = { version = "133.0-1" }
go = { version = "2:1.22.2-1" }
neovim = { version = "0.10.2-2" }
ripgrep = { version = "14.1.1-1" }
unzip = { version = "6.0-21" }
vscodium = { version = "1.95.3.24321-1" }
wezterm = { version = "20240203.110809.5046fc22-2" }
wget = { version = "1.25.0-1" }
npm = { version = "10.9.2-1" }
nodejs = { version = "23.3.0-1" }
lua = { version = "latest" }
zig = { version = "0.13.0-1" }
base = { version = "3-2" }
clang = { version = "18.1.8-4" }
git = { version = "2.47.1-1" }
jdk-openjdk = { version = "23.0.1.u0-1" }
texlive-latex = { version = "2024.2-3" }
texlive-latexrecommended = { version = "2024.2-3" }
neofetch = { version = "7.1.0-2" }
imagemagick = { version = "7.1.1.41-1" }
pandoc-cli = { version = "3.1.11.1-9" }
flameshot = { version = "12.1.0-5" }
libreoffice-fresh = { version = "24.8.3-1" }
zip = { version = "3.0-11" }
luarocks = { version = "3.11.1-2" }
spectacle = { version = "24.08.3-1" }
zoxide = { version = "0.9.6-1" }
python-pipx = { version = "1.7.1-1" }
tree-sitter-cli = { version = "0.24.3-1" }
zsh = { version = "5.9-5" }
dmd = { version = "1:2.109.1-1" }
dolphin = { version = "24.08.3-1" }
expac = { version = "10-11" }
joshuto = { version = "0.9.8-3" }
lua51 = { version = "5.1.5-12" }
netflix = { version = "1.0.9-1" }
network-manager-applet = { version = "1.36.0-1" }
networkmanager = { version = "1.50.0-1" }
oh-my-posh = { version = "24.12.0-1" }
onedrive-abraunegg = { version = "2.5.3-1" }
racket = { version = "8.15-1" }
texlive-fontsrecommended = { version = "2024.2-3" }
ueberzugpp = { version = "2.9.6-6" }
zoom = { version = "6.2.11-1" }
browsh = { version = "1.8.3-1" }
dmd-docs = { version = "1:2.109.1-1" }
htop = { version = "3.3.0-3" }
spotify-launcher = { version = "0.6.0-1" }
steam = { version = "1.0.0.81-2" }
tokei = { version = "12.1.2-2" }
vim = { version = "9.1.0866-1" }
wireplumber = { version = "0.5.7-1" }
xclip = { version = "0.13-6" }
yay = { version = "12.4.2-1" }
yay-debug = { version = "12.4.2-1" }
moreutils = { version = "0.70-1" }

[vscode]
"svelte.svelte-vscode" = { version = "109.3.3" }
"violetiapalucci.one-midnight" = { version = "1.0.0" }
"usernamehw.errorlens" = { version = "3.20.0" }
"tamasfe.even-better-toml" = { version = "0.21.0" }
"redhat.java" = { version = "1.37.0" }
"pkief.material-icon-theme" = { version = "5.15.0" }
"rust-lang.rust-analyzer" = { version = "0.3.2212" }
"vscodevim.vim" = { version = "1.29.0" }
"dalysoftware.unicodepalette" = { version = "1.0.4" }
"ultram4rine.vscode-choosealicense" = { version = "0.9.4" }
"gruntfuggly.todo-tree" = { version = "0.0.215" }
"aaron-bond.better-comments" = { version = "3.0.2" }
"yoavbls.pretty-ts-errors" = { version = "0.5.3" }
"catppuccin.catppuccin-vsc" = { version = "3.15.2" }
"catppuccin.catppuccin-vsc-icons" = { version = "1.17.0" }
"dbaeumer.vscode-eslint" = { version = "3.0.10" }
"dtoplak.vscode-glsllint" = { version = "1.9.0" }
"esbenp.prettier-vscode" = { version = "11.0.0" }
"kdarkhan.mips" = { version = "0.1.1" }
"llvm-vs-code-extensions.vscode-clangd" = { version = "0.1.33" }
"slevesque.shader" = { version = "1.1.5" }
"tauri-apps.tauri-vscode" = { version = "0.2.9" }
"undefined_publisher.vscode-cabin" = { version = "0.0.1" }
"yandeu.five-server" = { version = "0.3.1" }

[cargo]
cargo-update = { version = "v13.4.0" }
darling-installer = { version = "v0.1.2" }
cargo-cmd = { version = "v0.3.1" }
cd-pls = { version = "v0.1.7" }
splik = { version = "v0.2.5" }

[npm]
generator-code = { version = "1.8.5" }
yo = { version = "5.0.0" }
corepack = { version = "0.29.4" }
node-gyp = { version = "11.0.0" }
nopt = { version = "7.2.1" }
npm = { version = "10.9.2" }
semver = { version = "7.6.3" }
vsce = { version = "2.15.0" }
