[module]
arch = { version = "v0.1.8" }
vscode = { version = "v0.1.2" }
cargo = { version = "v0.1.2" }
npm = { version = "v0.1.1" }

[arch]
base-devel = { version = "1-1" }
cargo-wizard = { version = "0.2.2-1" }
discord = { version = "0.0.48-1" }
firefox = { version = "124.0.2-1" }
go = { version = "2:1.22.2-1" }
neovim = { version = "0.9.5-5" }
ripgrep = { version = "14.1.0-1" }
unzip = { version = "6.0-20" }
vscodium = { version = "1.88.0.24096-1" }
wezterm = { version = "20240203.110809.5046fc22-1" }
wget = { version = "1.24.5-1" }
npm = { version = "10.5.1-1" }
nodejs = { version = "21.7.2-1" }
lua = { version = "latest" }
zig = { version = "0.11.0-2" }
base = { version = "3-2" }
clang = { version = "17.0.6-1" }
git = { version = "2.44.0-1" }
gimp = { version = "latest" }
intellij-idea-community-edition = { version = "4:2024.1-2" }
jdk-openjdk = { version = "22.u36-1" }
texlive-latex = { version = "2024.0-3" }
texlive-latexrecommended = { version = "2024.0-3" }
neofetch = { version = "7.1.0-2" }
imagemagick = { version = "7.1.1.30-2" }
pandoc-cli = { version = "0.1.1.1-92" }
flameshot = { version = "12.1.0-3" }
libreoffice-fresh = { version = "24.2.2-2" }
zip = { version = "3.0-11" }
pacman-contrib = { version = "1.10.5-1" }
luarocks = { version = "3.11.0-1" }
spectacle = { version = "24.02.2-1" }

[vscode]
"svelte.svelte-vscode" = { version = "108.3.3" }
"violetiapalucci.one-midnight" = { version = "1.0.0" }
"usernamehw.errorlens" = { version = "3.16.0" }
"tamasfe.even-better-toml" = { version = "0.19.1" }
"redhat.java" = { version = "1.29.0" }
"pkief.material-icon-theme" = { version = "4.34.0" }
"rust-lang.rust-analyzer" = { version = "0.3.1916" }
"vscodevim.vim" = { version = "1.27.2" }
"dalysoftware.unicodepalette" = { version = "1.0.4" }
"ultram4rine.vscode-choosealicense" = { version = "0.9.4" }
"gruntfuggly.todo-tree" = { version = "0.0.215" }
"aaron-bond.better-comments" = { version = "3.0.2" }
"yoavbls.pretty-ts-errors" = { version = "0.5.3" }

[cargo]
cargo-update = { version = "v13.4.0" }
darling-installer = { version = "v0.1.2" }

[npm]
generator-code = { version = "1.8.5" }
yo = { version = "5.0.0" }
