[module]
arch = { version = "=1.0.81" }
vscode = { version = "=1.0.81" }

[arch]
base-devel = { version = "1-1" }
cargo-wizard = { version = "0.2.2-1" }
discord = { version = "0.0.48-1" }
firefox = { version = "124.0.2-1" }
go = { version = "2:1.22.2-1" }
neovim = { version = "0.9.5-5" }
ripgrep = { version = "14.1.0-1" }
unzip = { version = "6.0-20" }
vscodium = { version = "1.88.0.24096-1" }
wezterm = { version = "20240203.110809.5046fc22-1" }
wget = { version = "1.24.5-1" }

[vscode]
"svelte.svelte-vscode" = { version = "108.3.3" }
"violetiapalucci.one-midnight" = { version = "1.0.0" }
"usernamehw.errorlens" = { version = "3.16.0" }
"tamasfe.even-better-toml" = { version = "0.19.1" }
"redhat.java" = { version = "1.29.0" }
"pkief.material-icon-theme" = { version = "4.34.0" }
"rust-lang.rust-analyzer" = { version = "0.3.1916" }
"vscodevim.vim" = { version = "1.27.2" }
