[module]
arch = { version = "v0.1.8" }
vscode = { version = "v0.1.2" }
cargo = { version = "v0.1.2" }
npm = { version = "v0.1.1" }

[arch]
base-devel = { version = "1-1" }
cargo-wizard = { version = "0.2.2-2" }
discord = { version = "0.0.59-2" }
firefox = { version = "127.0.2-1" }
go = { version = "2:1.22.2-1" }
neovim = { version = "0.10.0-5" }
ripgrep = { version = "14.1.0-1" }
unzip = { version = "6.0-21" }
vscodium = { version = "1.91.0.24190-1" }
wezterm = { version = "20240203.110809.5046fc22-2" }
wget = { version = "1.24.5-3" }
npm = { version = "10.8.1-1" }
nodejs = { version = "22.4.1-1" }
lua = { version = "latest" }
zig = { version = "0.13.0-1" }
base = { version = "3-2" }
clang = { version = "18.1.8-1" }
git = { version = "2.45.2-1" }
jdk-openjdk = { version = "22.0.1.u0-1" }
texlive-latex = { version = "2024.2-2" }
texlive-latexrecommended = { version = "2024.2-2" }
neofetch = { version = "7.1.0-2" }
imagemagick = { version = "7.1.1.34-1" }
pandoc-cli = { version = "0.1.1.1-113" }
flameshot = { version = "12.1.0-3" }
libreoffice-fresh = { version = "24.2.4-2" }
zip = { version = "3.0-11" }
luarocks = { version = "3.11.1-1" }
spectacle = { version = "24.05.2-1" }
zoxide = { version = "0.9.4-2" }
python-pipx = { version = "1.6.0-1" }
tree-sitter-cli = { version = "0.22.6-1" }
zsh = { version = "5.9-5" }
dmd = { version = "1:2.109.1-1" }
dolphin = { version = "24.05.2-1" }
expac = { version = "10-10" }
joshuto = { version = "0.9.8-3" }
lua51 = { version = "5.1.5-12" }
netflix = { version = "1.0.7-1" }
network-manager-applet = { version = "1.36.0-1" }
networkmanager = { version = "1.48.4-1" }
oh-my-posh = { version = "21.23.1-1" }
onedrive-abraunegg = { version = "2.4.25-1" }
racket = { version = "8.13-1" }
texlive-fontsrecommended = { version = "2024.2-2" }
ueberzugpp = { version = "2.9.6-2" }
zoom = { version = "6.1.1-1" }
ghc = { version = "9.2.8-1" }
cabal-install = { version = "3.6.2.0-21" }

[vscode]
"svelte.svelte-vscode" = { version = "108.3.3" }
"violetiapalucci.one-midnight" = { version = "1.0.0" }
"usernamehw.errorlens" = { version = "3.16.0" }
"tamasfe.even-better-toml" = { version = "0.19.1" }
"redhat.java" = { version = "1.29.0" }
"pkief.material-icon-theme" = { version = "4.34.0" }
"rust-lang.rust-analyzer" = { version = "0.3.1916" }
"vscodevim.vim" = { version = "1.27.2" }
"dalysoftware.unicodepalette" = { version = "1.0.4" }
"ultram4rine.vscode-choosealicense" = { version = "0.9.4" }
"gruntfuggly.todo-tree" = { version = "0.0.215" }
"aaron-bond.better-comments" = { version = "3.0.2" }
"yoavbls.pretty-ts-errors" = { version = "0.5.3" }

[cargo]
cargo-update = { version = "v13.4.0" }
darling-installer = { version = "v0.1.2" }

[npm]
generator-code = { version = "1.8.5" }
yo = { version = "5.0.0" }
